vim.g.coc_global_extensions = {
  'coc-python',
  'coc-json',
  'coc-tsserver',
  'coc-css',
  'coc-yaml',
  'coc-sh',
  'coc-prettier',
  'coc-clangd',
  'coc-jedi',
  'coc-diagnostic',
  'coc-explorer',
  'coc-lists',
  'coc-rust-analyzer',
}
