name: Build and Push Docker Image

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            runner: ubuntu-latest
          - platform: linux/arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    outputs:
      digest-${{ matrix.platform }}: ${{ steps.build.outputs.digest }}
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/setup-buildx-action@v3

      - name: Build and Push
        id: build
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          tags: |
            ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}

  manifest:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create and Push Manifest
        uses: int128/docker-manifest-create-action@v2
        with:
          tags: |
            ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.IMAGE_NAME }}:${{ github.sha }}
            ${{ vars.DOCKERHUB_NAMESPACE }}/${{ vars.IMAGE_NAME }}:latest
          digests: |
            ${{ needs.build.outputs['digest-linux/amd64'] }}
            ${{ needs.build.outputs['digest-linux/arm64'] }}

